### PR TITLE
Enable manual mode for entering password

### PR DESCRIPTION
**Pull request by devdinu**
- When there's delay in connecting to vpn, the password is entered in terminal

There's no sync between window opening and password input, This change makes the `enter` step manual with password in clipboard.

### CODE REVIEW

**Comment by arunvelsriram** [comment]
Thanks for this PR. This feature is quite useful.

I have renamed `MANUAL_MODE` to `AUTOFILL` because I felt its short and more suitable. Can you mention about this feature in the readme?

**Comment by arunvelsriram** [comment]
@devdinu am thinking for making it an option like `lazy-connect -n`. what do you think?

**Comment by arunvelsriram** [comment]
`-disconnect, -connect -autofill` are hard to implement in shell script. Environment variable is lengthy so users might have to do an alias or use the history every time. `-n` is just an example we can use anything as an option.

**Comment by arunvelsriram** [comment]
Am leaning towards using an option instead of an env variable. Let me know if you can make the change and update the readme.

**Comment by arunvelsriram** [comment]
@devdinu gentle ping

**Comment by devdinu** [comment]
@arunvelsriram Updated the code, could you test again and merge.

**Comment by arunvelsriram** [comment]
@devdinu please rebase, squash the commits. The commit history is not required.

**Comment by arunvelsriram** [comment]
It's not working in my local machine.

```
cat: /Users/arunvelsriram/.config/lazy-connect/secret: No such file or directory
409:412: syntax error: Expected end of line but found real number. 
```
Its trying read secret from a local file. The secret is now stored in OS X Keychain.

Also please rebase and squash the commits to keep the history clean in master.

**Comment by devdinu** [comment]
@arunvelsriram Could you verify the functionality now, i've pushed some fixes.

**Comment by devdinu** [comment]
If autofill enabled, I wouldn't prefer to change my clipboard also we don't need it further, and we're copying to clipboard when its disabled.

**Comment by arunvelsriram** [comment]
Fixed in #16

**Pull request closed without merging**
